version: "3.9"
services:
  report2zabbix:
    image: "report2zabbix"
    container_name: monitoring
    environment: 
      HOST: ${HOST}
      BEAM_URL: ${BEAM_URL}
      PROXY_ID: ${PROXY_ID}
      ZABBIX_SERVER_URL: ${ZABBIX_SERVER_URL}
      ZABBIX_API_URL: ${ZABBIX_API_URL}
      KEY: ${KEY}
    